// embed-web/src/pages/settings.svelte
<script module lang="ts">
  import type { RouteMeta } from "@/lib/route-manifest";
  import { Settings } from "lucide-svelte";

  export const routeMeta: RouteMeta = {
    label: "设置",
    icon: Settings,
    order: 2,
  };
</script>

<script lang="ts">
  import {
    getThemeMode,
    setThemeMode,
    type ThemeMode,
  } from "@/lib/theme.svelte";
  import { showAlert, showConfirm, showToast } from "@/lib/feedback.svelte";
  import { Sun, Moon, Monitor } from "lucide-svelte";

  let deviceName = $state("ESP32-S3-IoT");

  const themeOptions: { value: ThemeMode; label: string; icon: typeof Sun }[] =
    [
      { value: "system", label: "跟随系统", icon: Monitor },
      { value: "light", label: "亮色", icon: Sun },
      { value: "dark", label: "暗色", icon: Moon },
    ];
</script>

<div class="page">
  <div class="page-header">
    <h1>设置</h1>
    <p class="subtitle">设备配置</p>
  </div>

  <div class="settings-group">
    <h2 class="group-title">外观</h2>
    <div class="settings-list">
      <div class="setting-item">
        <span class="setting-label">主题模式</span>
        <div class="theme-picker">
          {#each themeOptions as opt}
            <button
              class="theme-btn"
              class:active={getThemeMode() === opt.value}
              onclick={() => setThemeMode(opt.value)}
              aria-label={opt.label}
            >
              <opt.icon size={16} />
              <span>{opt.label}</span>
            </button>
          {/each}
        </div>
      </div>
    </div>
  </div>

  <div class="settings-group">
    <h2 class="group-title">设备</h2>
    <div class="settings-list">
      <label class="setting-item">
        <span class="setting-label">设备名称</span>
        <input type="text" bind:value={deviceName} class="setting-input" />
      </label>
      <div class="setting-item">
        <span class="setting-label">固件版本</span>
        <span class="setting-value">v1.0.0</span>
      </div>
      <div class="setting-item">
        <span class="setting-label">SDK 版本</span>
        <span class="setting-value">ESP-IDF 5.x</span>
      </div>
    </div>
  </div>

  <div class="settings-group">
    <h2 class="group-title">网络</h2>
    <div class="settings-list">
      <div class="setting-item">
        <span class="setting-label">IP 地址</span>
        <span class="setting-value">192.168.4.1</span>
      </div>
      <div class="setting-item">
        <span class="setting-label">MAC 地址</span>
        <span class="setting-value">AA:BB:CC:DD:EE:FF</span>
      </div>
    </div>
  </div>

  <div class="settings-group">
    <h2 class="group-title">操作</h2>
    <div class="settings-list">
      <div class="setting-item action">
        <button
          class="btn"
          onclick={() => {
            showAlert("OTA 升级功能待实现", "提示");
            showToast("当前已是最新版本", "info");
          }}>检查更新</button
        >
      </div>
      <div class="setting-item action">
        <button
          class="btn danger"
          onclick={async () => {
            const r = await showConfirm("确定要重启设备吗？", "重启设备", true);
            if (r === "ok") showToast("设备正在重启…", "success");
            else showToast("已取消重启", "warning");
          }}>重启设备</button
        >
      </div>
    </div>
  </div>
</div>

<style>
  .page-header {
    margin-bottom: 24px;
  }
  .page-header h1 {
    font-size: 28px;
    margin: 0 0 4px;
  }
  .subtitle {
    color: var(--text);
    font-size: 14px;
  }
  .settings-group {
    margin-bottom: 24px;
  }
  .group-title {
    font-size: 13px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text);
    margin: 0 0 8px;
    padding: 0 4px;
  }
  .settings-list {
    display: flex;
    flex-direction: column;
    gap: 1px;
    background: var(--border);
    border: 1px solid var(--border);
    border-radius: 12px;
    overflow: hidden;
  }
  .setting-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 14px 16px;
    background: var(--card-bg);
    min-height: 24px;
  }
  .setting-label {
    font-size: 15px;
    color: var(--text-h);
  }
  .setting-value {
    font-size: 14px;
    color: var(--text);
    font-family: var(--mono);
  }
  .setting-input {
    text-align: right;
    border: none;
    background: transparent;
    color: var(--accent);
    font-size: 14px;
    width: 140px;
    outline: none;
    font-family: var(--mono);
  }
  .setting-item.action {
    justify-content: center;
    padding: 8px 16px;
  }
  .btn {
    width: 100%;
    padding: 10px;
    border: none;
    border-radius: 8px;
    background: var(--accent);
    color: #fff;
    font-size: 15px;
    font-weight: 500;
    cursor: pointer;
    -webkit-tap-highlight-color: transparent;
  }
  .btn:active {
    opacity: 0.85;
  }
  .btn.danger {
    background: #ef4444;
  }
  .theme-picker {
    display: flex;
    gap: 4px;
    background: var(--border);
    border-radius: 8px;
    padding: 3px;
  }
  .theme-btn {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 5px 10px;
    border: none;
    border-radius: 6px;
    background: transparent;
    color: var(--muted);
    font-size: 12px;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.15s;
    white-space: nowrap;
    -webkit-tap-highlight-color: transparent;
  }
  .theme-btn.active {
    background: var(--card-bg);
    color: var(--accent);
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  }
</style>

// embed-web/src/pages/settings.tsx
import { createSignal, For } from "solid-js";
import { Dynamic } from "solid-js/web";
import { Monitor, Moon, Settings, Sun } from "lucide-solid";
import type { IconComponent, RouteMeta } from "@/lib/route-manifest";
import { setThemeMode, themeMode, type ThemeMode } from "@/lib/theme";
import { showAlert, showConfirm, showToast } from "@/lib/feedback";
import { cx } from "@/lib/cx";
import styles from "./settings.module.css";

export const routeMeta: RouteMeta = {
  label: "设置",
  icon: Settings,
  order: 2,
};

const themeOptions: { value: ThemeMode; label: string; icon: IconComponent }[] = [
  { value: "system", label: "跟随系统", icon: Monitor },
  { value: "light", label: "亮色", icon: Sun },
  { value: "dark", label: "暗色", icon: Moon },
];

export default function SettingsPage() {
  const [deviceName, setDeviceName] = createSignal("ESP32-S3-IoT");

  const checkUpdate = () => {
    void showAlert("OTA 升级功能待实现", "提示");
    showToast("当前已是最新版本", "info");
  };

  const rebootDevice = async () => {
    const result = await showConfirm("确定要重启设备吗？", "重启设备", true);
    if (result === "ok") {
      showToast("设备正在重启…", "success");
    } else {
      showToast("已取消重启", "warning");
    }
  };

  return (
    <div class="page">
      <div class={cx("page-header", styles.pageHeader)}>
        <h1>设置</h1>
        <p class={cx("subtitle", styles.subtitle)}>设备配置</p>
      </div>

      <div class={styles.settingsGroup}>
        <h2 class={styles.groupTitle}>外观</h2>
        <div class={styles.settingsList}>
          <div class={styles.settingItem}>
            <span class={styles.settingLabel}>主题模式</span>
            <div class={styles.themePicker}>
              <For each={themeOptions}>
                {(option) => (
                  <button
                    class={cx(styles.themeBtn, themeMode() === option.value && styles.active)}
                    onClick={() => setThemeMode(option.value)}
                    aria-label={option.label}
                    aria-pressed={themeMode() === option.value}
                  >
                    <Dynamic component={option.icon} size={16} />
                    <span>{option.label}</span>
                  </button>
                )}
              </For>
            </div>
          </div>
        </div>
      </div>

      <div class={styles.settingsGroup}>
        <h2 class={styles.groupTitle}>设备</h2>
        <div class={styles.settingsList}>
          <label class={styles.settingItem}>
            <span class={styles.settingLabel}>设备名称</span>
            <input
              type="text"
              value={deviceName()}
              onInput={(event) => setDeviceName(event.currentTarget.value)}
              class={styles.settingInput}
            />
          </label>
          <div class={styles.settingItem}>
            <span class={styles.settingLabel}>固件版本</span>
            <span class={styles.settingValue}>v1.0.0</span>
          </div>
          <div class={styles.settingItem}>
            <span class={styles.settingLabel}>SDK 版本</span>
            <span class={styles.settingValue}>ESP-IDF 5.x</span>
          </div>
        </div>
      </div>

      <div class={styles.settingsGroup}>
        <h2 class={styles.groupTitle}>网络</h2>
        <div class={styles.settingsList}>
          <div class={styles.settingItem}>
            <span class={styles.settingLabel}>IP 地址</span>
            <span class={styles.settingValue}>192.168.4.1</span>
          </div>
          <div class={styles.settingItem}>
            <span class={styles.settingLabel}>MAC 地址</span>
            <span class={styles.settingValue}>AA:BB:CC:DD:EE:FF</span>
          </div>
        </div>
      </div>

      <div class={styles.settingsGroup}>
        <h2 class={styles.groupTitle}>操作</h2>
        <div class={styles.settingsList}>
          <div class={cx(styles.settingItem, styles.action)}>
            <button class={styles.btn} onClick={checkUpdate}>
              检查更新
            </button>
          </div>
          <div class={cx(styles.settingItem, styles.action)}>
            <button class={cx(styles.btn, styles.danger)} onClick={() => void rebootDevice()}>
              重启设备
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
